### Notes ###
# raw files should have the .raw file extension so they can be found by spectral
### Required Packages ###
# SpectralPython (spectral), tqdm, NumPy, SciPy, Matplotlib

### Imports ###
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from scipy.optimize import least_squares
import spectral.io.envi as envi
from spectral import imshow, view_cube
import tqdm

### Constants ###
h = 6.626e-34 # Planck's constant
c = 299792458 # Speed of light
k = 1.380649e-23 # Boltzmann constant
b = 2.89777e-3 # Wien's constant

### Other Global Variables ###
units = None
wavelengths = None
pixel = None
spectrum = None

### Helper Functions ###

def blackbody(l, T, e, offset=0):
    """Blackbody radiation equation
    Input: l: wavelength, T: temperature, e: emissivity, 
            offset: used in fitting to account for stray light in the data
    Output: intensity of a blackbody at the given parameters"""
    return (e * ((2 * h * c**2) / l**5) * (1 / (np.exp((h * c) / (l * k * T)) - 1))) + offset

def construct_paths(folder_path):
    """ Constructs the paths to each of the relevant data files
    Input: path to hyperspectral data folder
    Output: list of paths to [raw hdr, raw raw, white reference hdr, white reference raw, 
                            dark reference hdr, dark reference raw, frame index file] """
    print("Constructing paths...")
    retval = []
    retval.append(folder_path + "/raw.hdr")
    retval.append(folder_path + "/raw.raw")
    retval.append(folder_path + "/whiteReference.hdr")
    retval.append(folder_path + "/whiteReference.raw")
    retval.append(folder_path + "/darkReference.hdr")
    retval.append(folder_path + "/darkReference.raw")
    retval.append(folder_path + "/frameIndex.txt")
    return retval

def load_data(paths, quiet=False):
    """Input: paths list generated by (or in format of) construct_paths
    Output: hyperspectral tensor corrected by the white and dark references"""
    print("Loading data...")
    data_ref = envi.open(paths[0], paths[1])
    white_ref = envi.open(paths[2], paths[3])
    dark_ref = envi.open(paths[4], paths[5])

    white_tensor = np.array(white_ref.load())
    dark_tensor = np.array(dark_ref.load())
    data_tensor = np.array(data_ref.load())

    corrected_data = np.divide(
    np.subtract(data_tensor, dark_tensor),
    np.subtract(white_tensor, dark_tensor))

    if not quiet:
        print(corrected_data)
    return corrected_data

def get_bands(paths, quiet=False):
    """Input: paths list generated by (or in format of) construct_paths
    Output: (Array of wavelength bands, wavelength units string)"""
    print("Getting wavelength bands...")
    global wavelengths
    global units
    file = open(paths[0], 'r')
    text = file.read()

    start_id = "\nwavelength = {\n"
    start_index = text.find(start_id) + len(start_id)
    end_id = "\n}\n;AOI height"
    end_index = text.find(end_id)
    wavelengths = text[start_index:end_index]
    wavelengths = np.array(wavelengths.split("\n,"), dtype=np.float32)

    units_id = "wavelength units = "
    units_index = text.find(units_id) + len(units_id)
    units = text[units_index:text.find(start_id)]

    if not quiet:
        print(f"Units = {units}")
        print(f"Number wavelengths = {len(wavelengths)}")
        print(f"Wavelengths: {wavelengths}")

    return None

def plot_spectrum(quiet=False):
    """Plots the selected spectrum
    Input: None (uses global variables), Output: None"""
    print("Plotting spectrum...")
    if not quiet:
        plt.figure(figsize=(5,5))
        plt.scatter(wavelengths, spectrum, s=7)
        plt.title(f"Spectrum for Position ({pixel[0]}, {pixel[1]})", fontsize=17)
        plt.xlabel(f"Wavelength [{units}]", fontsize=12)
        plt.xticks(fontsize=10)
        plt.ylabel("Irradiance [arb. units]", fontsize=12)
        plt.yticks([])
        plt.show()

    return None

def fit_spectrum(quiet=False):
    """Fits the selected spectrum
    Input: None (uses global variables)
    Output: Fitted parameters, final least squares cost"""
    print("\nIf this test fails, check lower in this function to adjust wavelenght unit conversion to m")
    print("Checking that units are nm...")
    assert(units == "nm")
    print("Passed")
    print("Fitting spectrum...")

    # params = [a0, a1, a2, offset, T]
    params0 = np.array([1, 1, 1, 0.1, 1000])
    def intensity(params, l):
        e = params[0] + (params[1] * l) + (params[2] * l**2)
        return blackbody(l, params[4], e, params[3])
    
    def residuals(params):
        result = []
        for i in range(len(wavelengths)):
            Si = intensity(params, wavelengths[i] * 1e-9) # assuming units are nm
            St = spectrum[i]
            result.append(Si - St)
        return np.array(result)

    result = least_squares(residuals, params0)

    if not quiet:
        yfit = []
        for l in wavelengths:
            yfit.append(intensity(result.x, l * 1e-9))

        plt.figure(figsize=(5,5))
        plt.scatter(wavelengths, spectrum, s=5)
        plt.scatter(wavelengths, yfit, s=5)
        plt.title(f"Fitted Spectrum for Position ({pixel[0]}, {pixel[1]})", fontsize=15)
        plt.xlabel(f"Wavelength [{units}]", fontsize=12)
        plt.xticks(fontsize=10)
        plt.ylabel("Intensity [arb. units]", fontsize=12)
        plt.yticks([])
        plt.legend(["Actual", "Fitted"], fontsize=10)
        plt.show()

    return result.x, result.cost

### Main ###

def main():
    global pixel
    global spectrum
    folder_path = input("Enter the file path to your hyperspectral data folder: ")
    paths = construct_paths(folder_path)
    data = load_data(paths, quiet=True)
    _ = get_bands(paths, quiet=True)

    while True:
        pixel = input("\nEnter the pixel you want to analyze 'frame,position' or 'exit' to end program: ")
        if pixel == "exit": return

        pixel = np.array(pixel.split(","), dtype=np.int64)
        x, y = pixel[0], pixel[1]
        spectrum = data[x][y]
        assert(len(spectrum) == len(wavelengths))

        _ = plot_spectrum()
        result, cost = fit_spectrum()
        print(f"\nTemperature = {result[4]} K\n")
        print(f"Emissivity = ({result[0]}) + ({result[1]} * wavelength) + ({result[2]} * wavelength^2)")
        print(f"Stray Light Offset = {result[3]}")
        print(f"Final Cost = {cost}")
    
if __name__ == "__main__": main()